# Generated by Django 4.2.2 on 2023-07-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_name', models.CharField(max_length=100)),
                ('Parent_key', models.CharField(max_length=100)),
                ('children_name', models.CharField(max_length=100)),
                ('children_key', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
