# Generated by Django 4.2.2 on 2023-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0004_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
