# Generated by Django 4.2.2 on 2023-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0005_alter_person_date_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
