# Generated by Django 4.2.2 on 2023-07-25 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0007_remove_person_date_person_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='time',
        ),
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
