# Generated by Django 4.2.2 on 2023-07-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0008_remove_person_time_person_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
