# Generated by Django 4.2.2 on 2023-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0010_person_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='Parent_image',
        ),
        migrations.AddField(
            model_name='person',
            name='children_image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
    ]
