# Generated by Django 4.2.2 on 2023-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0012_alter_person_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
